config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
#get method route is /about controller is about and function is index
get "about", to: "about#index" #"about" or "/about" is same
root to:"main#index"  #root "main#index" WROKS SIMILARLY
get "sign_up", to: "registrations#new"
post "sign_up", to: "registrations#create"
get "sign_in", to: "sessions#new"
post "sign_in", to: "sessions#create"
delete "logout", to: "sessions#destroy"
get "edit_password", to:"password#edit"
patch "edit_password", to:"password#update"
get "edit_password/reset", to:"password_reset#new"
post "edit_password/reset", to:"password_reset#create"
get "edit_password/reset/edit", to:"password_reset#edit"
patch "edit_password/reset/edit", to:"password_reset#update" 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, msg: "not valid" }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController #for functionality of rails
    def index ##rails looks for index.html.erb file inside views in about folder
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user #this action runs before any other action
    def set_current_user ##rails looks for index.html.erb file inside views in about folder    
        if(session[:user_id])
            #@user=User.find(session[:user_id]) #find is used when we are sure we will find this is
            # @user=User.find_by(id: session[:user_id])
            Current.user = User.find_by(id: session[:user_id])
        end
    end

    def redirect_user_sign_in!
        redirect_to sign_in_path, alert: "you need to be signed to do that" if Current.user.nil?
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController #for functionality of rails
    def index ##rails looks for index.html.erb file inside views in about folder    
        # if(session[:user_id])
        #     #@user=User.find(session[:user_id]) #find is used when we are sure we will find this is
        #     @user=User.find_by(id: session[:user_id])
        #end
    end
end

app/controllers/password_controller.rb
class PasswordController < ApplicationController
    before_action :redirect_user_sign_in!
    def edit
    end
    def update
        if Current.user.update(password_params)
            redirect_to root_path,notice:"updated password"
        else
            render :edit
        end
    end
    private
    def password_params
        params.require(:user).permit(:password,:password_confirmation)
    end
end

app/controllers/password_reset_controller.rb
class PasswordResetController < ApplicationController
    def new
    end
    def create
        @user=User.find_by(email:params[:email])
        if @user.present?
            PasswordMailer.with(user: @user).reset.deliver_now
        end
        redirect_to root_path,notice:"if account with this email exists we have sent the link to reset password"
    end
    def edit
        @user=User.find_signed(params[:token],purpose: "edit_password_reset")
    rescue Exception
        redirect_to sign_in_path,alert:"ypur token expired"
    end
    def update
        @user=User.find_signed!(params[:token],purpose: "edit_password_reset")
        if @user.update(password_params)
            redirect_to sign_in_path ,notice:"your password was reset successfully"
        else
            render :edit
        end
    end
    private 
    def password_params
        params.require(:user).permit(:password,:password_confirmation)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def new 
        @user=User.new
    end
    def create
        @user=User.new(user_params)
        #@user=User.new(params[:user])
        #@user=User.new(email: "ftgyhuj", password: "fghj")
        if @user.save
            session[:user_id]=@user.id
            redirect_to root_path , notice: "created user"
        else
            render :new
        end
    end

    private 
    def user_params
        params.require(:user).permit(:email,:password,:password_confirmation)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
    def create
        user=User.find_by(email: params[:email])
        if(user.present? && user.authenticate(params[:password]))
            session[:user_id]=user.id
            redirect_to root_path, notice: "logged in"
        else
            render :new
        end
    end
    def destroy
        session[:user_id]= nil
        redirect_to root_path ,notice: "Logged out"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About us</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>

  <body>
    <%= render partial: "shared/navbar" %> 
    <%= render partial: "shared/flash" %> 
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
    <h1>welcome to root</h1>

    <%
=begin%>
 <% if(@user) %>
    Logged in as <%= @user.email %>
    <%=button_to "Logout",logout_path,method: :delete %>
    <% end %> 
<%
=end%>
</div>

app/views/password/edit.html.erb
<h1>edit password</h1>
<%= form_with model: Current.user ,url: edit_password_path ,method: :patch do |form| %>
<% if @user && @user.errors.any? %>
    <div class="alert alert-danger">
    <% @user.errors.full_messages.each do |msg| %>
        <div><%= msg %></div>
    <% end %>
    </div>
<% end %>
<div class="mb-3">
    <%= form.label :password %>
    <%= form.password_field :password , class: "form-control", placeholder: "enter password" %>
</div>
<div class="mb-3">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation ,class: "form-control",placeholder: "enter password_confirmation" %>
</div>

<div class="mb-3">
    <%= form.submit "update password", class: "btn btn-primary" %>
</div>
<% end %>

app/views/password_reset/edit.html.erb
<h1>reset your password</h1>
<%= form_with model: @user,url: edit_password_reset_edit_path(token:params[:token]), method: :patch do |form| %>
<div class="mb-3">
    <%= form.label :password %>
    <%= form.password_field :password , class: "form-control", placeholder: "enter password" %>
</div>
<div class="mb-3">
    <%= form.label :email %>
    <%= form.password_field :password_confirmation , class: "form-control", placeholder: "enter password_confirmation" %>
</div>
<div class="mb-3">
    <%= form.submit "reset password" ,class: "btn btn-primary"%>
</div>
<% end %>

app/views/password_reset/new.html.erb
<h1>forgot your password</h1>
<%= form_with url: edit_password_reset_path do |form| %>
<div class="mb-3">
    <%= form.label :email %>
    <%= form.text_field :email , class: "form-control", placeholder: "enter email" %>
</div>

<div class="mb-3">
    <%= form.submit "reset your password" ,class: "btn btn-primary"%>
</div>
<% end %>

app/views/shared/_flash.html.erb
<div>
<% flash[:msg1] %>
<% flash[:msg2] %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "About", about_path, class:"nav-link" %>
        <%
        # link_to is a helper refers to text "About"
        # about_path means url /about
=begin%>
 <a class="nav-link" href="about">About</a> 
<%
=end%>
      </li>
    </ul>
    <ul class="navbar-nav mr-auto">
    <% if Current.user %>
        <li class="nav-item">
          <%= link_to Current.user.email, edit_password_path,class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= button_to "Logout", logout_path, method: :delete, class:"nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign_up", sign_up_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
         <%= link_to "Sign_in", sign_in_path, class:"nav-link" %>
        </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>